"""Live signals page."""
from __future__ import annotations

import pandas as pd
import requests
import streamlit as st

from app.config.settings import settings

API_BASE = f"http://localhost:{settings.api.port}/api/v1"


def _fetch(endpoint: str, fallback=None):
    try:
        r = requests.get(f"{API_BASE}/{endpoint}", timeout=5)
        r.raise_for_status()
        return r.json()
    except Exception:
        return fallback


def render():
    st.title("⚡ Live Signals")
    st.caption("Signals generated by active strategies. Paper only — manual execution required.")

    # Filters
    col1, col2, col3 = st.columns(3)
    with col1:
        asset_filter = st.selectbox("Asset", ["All", "BTCUSDT", "XAUUSD", "EURUSD"])
    with col2:
        direction_filter = st.selectbox("Direction", ["All", "LONG", "SHORT"])
    with col3:
        limit = st.slider("Max signals", 10, 200, 50)

    if st.button("🔄 Refresh"):
        st.rerun()

    # Fetch
    endpoint = f"signals?limit={limit}"
    if asset_filter != "All":
        endpoint += f"&asset={asset_filter}"
    signals = _fetch(endpoint, fallback=[])

    if not signals:
        st.info("No signals found. The paper engine may not be running.")
        return

    df = pd.DataFrame(signals)

    # Apply direction filter
    if direction_filter != "All":
        df = df[df["direction"] == direction_filter]

    if df.empty:
        st.warning("No signals match the current filters.")
        return

    # Render signal cards
    for _, row in df.iterrows():
        direction = str(row.get("direction", ""))
        is_long = direction == "LONG"
        direction_color = "#00ff88" if is_long else "#ff4466"
        direction_arrow = "▲ LONG" if is_long else "▼ SHORT"

        robustness = str(row.get("robustness", ""))
        rob_color = {"ROBUST": "#00ff88", "ACCEPTABLE": "#ffaa00",
                     "FRAGILE": "#ff8800", "OVERFIT": "#ff4466"}.get(robustness, "#888")

        with st.container():
            st.markdown(
                f"""
                <div style="background:#111827;border:1px solid #1f2d47;border-radius:8px;
                            padding:16px 20px;margin-bottom:12px;">
                  <div style="display:flex;justify-content:space-between;align-items:center;">
                    <span style="font-family:'JetBrains Mono',monospace;font-size:1.1rem;
                                 font-weight:700;">{row.get('asset','')}
                      <span style="color:{direction_color};margin-left:12px;">{direction_arrow}</span>
                    </span>
                    <span style="color:{rob_color};font-size:0.8rem;font-weight:600;">
                      ● {robustness}
                    </span>
                  </div>
                  <div style="margin-top:10px;display:grid;grid-template-columns:repeat(4,1fr);gap:8px;">
                    <div><small style="color:#888;">Strategy</small><br><code>{row.get('strategy','')}</code></div>
                    <div><small style="color:#888;">Timeframe</small><br><code>{row.get('timeframe','')}</code></div>
                    <div><small style="color:#888;">Entry</small><br>
                         <code style="color:#00d4ff;">{float(row.get('entry',0)):.4f}</code></div>
                    <div><small style="color:#888;">ATR</small><br>
                         <code>{float(row.get('atr',0)):.4f}</code></div>
                    <div><small style="color:#888;">Stop Loss</small><br>
                         <code style="color:#ff4466;">{float(row.get('stop_loss',0)):.4f}</code></div>
                    <div><small style="color:#888;">Take Profit</small><br>
                         <code style="color:#00ff88;">{float(row.get('take_profit',0)):.4f}</code></div>
                    <div><small style="color:#888;">Generated</small><br>
                         <code style="font-size:0.75rem;">{str(row.get('generated_at',''))[:16]}</code></div>
                  </div>
                  <div style="margin-top:8px;color:#888;font-size:0.8rem;font-style:italic;">
                    {row.get('reason','')}
                  </div>
                </div>
                """,
                unsafe_allow_html=True,
            )
