"""
Core domain models. These are pure data structures — no DB logic here.
All fields use type hints. Pydantic used for validation where needed.
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.core.enums import (
    AssetSymbol,
    EngineState,
    ExitReason,
    MarketRegime,
    RiskLevel,
    RobustnessLabel,
    SignalDirection,
    StrategyFamily,
    Timeframe,
    TradeStatus,
)


# ---------------------------------------------------------------------------
# Market data
# ---------------------------------------------------------------------------

@dataclass
class OHLCV:
    """Single OHLCV candle."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    asset: AssetSymbol = AssetSymbol.BTCUSDT
    timeframe: Timeframe = Timeframe.H1


@dataclass
class MarketSnapshot:
    """Current state of an asset's market data."""
    asset: AssetSymbol
    timeframe: Timeframe
    last_candle: OHLCV
    current_atr: float
    regime: MarketRegime = MarketRegime.UNKNOWN
    fetched_at: datetime = field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Signals
# ---------------------------------------------------------------------------

class Signal(BaseModel):
    """A trading signal generated by a strategy."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    asset: AssetSymbol
    strategy_name: str
    strategy_family: StrategyFamily
    timeframe: Timeframe
    direction: SignalDirection
    entry_price: float
    stop_loss: float
    take_profit: float
    atr: float
    regime: MarketRegime = MarketRegime.UNKNOWN
    robustness_label: RobustnessLabel = RobustnessLabel.ACCEPTABLE
    confidence_score: float = 0.5  # 0.0 - 1.0
    reason: str = ""
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True


# ---------------------------------------------------------------------------
# Trades
# ---------------------------------------------------------------------------

class PaperTrade(BaseModel):
    """A paper trade — open or closed position."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    signal_id: str
    asset: AssetSymbol
    strategy_name: str
    timeframe: Timeframe
    direction: SignalDirection
    entry_price: float
    stop_loss: float
    take_profit: float
    quantity: float = 1.0  # notional units
    status: TradeStatus = TradeStatus.OPEN
    exit_price: Optional[float] = None
    exit_reason: Optional[ExitReason] = None
    realized_pnl: Optional[float] = None
    unrealized_pnl: Optional[float] = None
    opened_at: datetime = Field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        use_enum_values = True

    def compute_unrealized_pnl(self, current_price: float) -> float:
        """Compute unrealized PnL given current price."""
        if self.direction == SignalDirection.LONG or self.direction == "LONG":
            return (current_price - self.entry_price) * self.quantity
        else:
            return (self.entry_price - current_price) * self.quantity

    def close(self, exit_price: float, exit_reason: ExitReason) -> None:
        """Close this trade."""
        self.exit_price = exit_price
        self.exit_reason = exit_reason
        self.status = TradeStatus.CLOSED
        self.closed_at = datetime.utcnow()
        self.realized_pnl = self.compute_unrealized_pnl(exit_price)
        self.unrealized_pnl = None


# ---------------------------------------------------------------------------
# Strategy config / metadata
# ---------------------------------------------------------------------------

@dataclass
class StrategyConfig:
    """User-facing configuration for a strategy instance."""
    name: str
    family: StrategyFamily
    asset: AssetSymbol
    timeframe: Timeframe
    parameters: Dict[str, Any] = field(default_factory=dict)
    enabled: bool = True
    tags: List[str] = field(default_factory=list)


@dataclass
class BacktestResult:
    """Results from a single backtest run."""
    strategy_name: str
    asset: AssetSymbol
    timeframe: Timeframe
    parameters: Dict[str, Any]

    # Core metrics
    total_return_pct: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    sortino_ratio: float = 0.0
    max_drawdown_pct: float = 0.0
    recovery_factor: float = 0.0
    expectancy: float = 0.0
    total_trades: int = 0
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0

    # Meta
    in_sample: bool = True
    period_start: Optional[datetime] = None
    period_end: Optional[datetime] = None
    robustness_label: RobustnessLabel = RobustnessLabel.INSUFFICIENT_DATA
    robustness_score: float = 0.0
    notes: str = ""


@dataclass
class WalkForwardResult:
    """Aggregated walk-forward optimization results."""
    strategy_name: str
    asset: AssetSymbol
    timeframe: Timeframe
    windows: List[Dict[str, Any]] = field(default_factory=list)
    wf_efficiency: float = 0.0  # out-of-sample / in-sample ratio
    consistency_score: float = 0.0  # how stable across windows
    passed: bool = False


# ---------------------------------------------------------------------------
# Risk state
# ---------------------------------------------------------------------------

@dataclass
class RiskState:
    """Current risk state of the paper engine."""
    level: RiskLevel = RiskLevel.NORMAL
    engine_state: EngineState = EngineState.RUNNING
    daily_drawdown_pct: float = 0.0
    weekly_drawdown_pct: float = 0.0
    total_drawdown_pct: float = 0.0
    open_positions_count: int = 0
    last_updated: datetime = field(default_factory=datetime.utcnow)
    emergency_reason: Optional[str] = None
    no_new_signals: bool = False


# ---------------------------------------------------------------------------
# Engine health / heartbeat
# ---------------------------------------------------------------------------

@dataclass
class HeartbeatRecord:
    """Single heartbeat ping from the engine."""
    service_name: str
    status: str  # "ok" | "degraded" | "error"
    timestamp: datetime = field(default_factory=datetime.utcnow)
    message: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EquitySnapshot:
    """Point-in-time equity snapshot."""
    timestamp: datetime
    equity: float
    open_pnl: float
    realized_pnl: float
    open_positions: int
